apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeapp
  labels:
    app: cafeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeapp
  template:
    metadata:
      labels:
        app: cafeapp
    spec:
      containers:
      - name: staticwebapp99 
        image: shailadocker123/cafeapp2:v2
        ports:
        - containerPort: 80
